### ISSUE TITLE
Invalid HTML if product name or description contains HTML entities

### ISSUE THREAD

**Issue by lat9** [numinix/numinix_structured_data_public#2]
If a product's name or description contains, for example, double-quotes (") then the HTML generated by this plugin is invalid.

I made the following changes to /includes/classes/observers/nmx_structured_data/class.product_listing.php to correct the issue:

       echo '<meta itemprop="name" content="'.htmlentities ($sdlisting->fields['products_name'], ENT_COMPAT, CHARSET).'"/>';  //-20140925-lat9-Add htmlentities
 
       echo '<meta itemprop="description" content="'.htmlentities (zen_clean_html(stripslashes(zen_get_products_description($sdlisting->fields['products_id']))), ENT_COMPAT, CHARSET).'"/>';  //-20140925-lat9-Add htmlentities

**Comment by Jujhar** [comment]
Thank you for your input we have updated our product to include this change.

**Comment by Jujhar** [comment]
close
